---


- name: deplaa liigasovelluksen
  hosts: liiga

  vars:
    base: ..

  tasks:
    - shell: "python bumped.py {{ base }}/pom.xml"
      register: new_version
      delegate_to: localhost
      when: bump is defined and bump

    - shell: "python bumped.py {{ base }}/pom.xml dontbump"
      register: version
      delegate_to: localhost
      when: bump is not defined or not bump

    - name: versiobump
      shell: "mvn -s settings.xml versions:set -DnewVersion={{ new_version.stdout }}"
      args:
        chdir: "{{ base }}"
      delegate_to: localhost
      when: bump is defined and bump

    - file:
        dest: "{{ base }}/pom.xml.versionsBackup"
        state: absent
      delegate_to: localhost
      when: bump is defined

    - name: kommitoi versiobump
      shell: "git ci -m 'version bump to {{ new_version.stdout }}' pom.xml"
      args:
        chdir: "{{ base }}"
      delegate_to: localhost
      when: bump is defined

    - name: buildaa
      shell: "mvn -s settings.xml clean package"
      args:
        chdir: "{{ base }}"
      delegate_to: localhost

    - name: kopsaa jarri kohdekoneelle
      copy:
        src: "{{ base }}/target/liiga-{{ new_version.stdout }}.jar"
        dest: ./liiga-{{ new_version.stdout }}.jar
      when: bump is defined

    - name: kopsaa jarri kohdekoneelle
      copy:
        src: "{{ base }}/target/liiga-{{ version.stdout }}.jar"
        dest: ./liiga-{{ version.stdout }}.jar
      when: bump is not defined

