---


- name: deplaa liigasovelluksen
  hosts: liiga

  vars:
    base: ..

  tasks:
    - name: versiobump
      shell: "mvn -s settings.xml versions:set -DnewVersion={{ version }}"
      args:
        chdir: "{{ base }}"
      delegate_to: localhost
      when: bump is defined and bump

    - file:
        dest: "{{ base }}/pom.xml.versionsBackup"
        state: absent
      delegate_to: localhost
      when: bump is defined

    - name: kommitoi versiobump
      shell: "git ci -m 'version bump to {{ version }}' pom.xml"
      args:
        chdir: "{{ base }}"
      delegate_to: localhost
      when: bump is defined

    - name: buildaa
      shell: "mvn -s settings.xml clean package"
      args:
        chdir: "{{ base }}"
      delegate_to: localhost

    - name: kopsaa
      copy:
        src: "{{ base }}/target/liiga-{{ version }}.jar"
        dest: ./liiga-{{ version }}.jar

